# Load Packages
```{r}
library(Seurat)
library(ggplot2)
library(harmony)
```

# Load combined seurat object cluster
```{r}
rna_tcr <- readRDS('../../Seurat_Objects/FROM_STEP_2_Combined/rna_tcr_combined.rds')

# RNA Normalization
DefaultAssay(rna_tcr) <- "RNA"
rna_tcr <- NormalizeData(rna_tcr)
rna_tcr <- FindVariableFeatures(rna_tcr)
rna_tcr <- ScaleData(rna_tcr)
rna_tcr <- RunPCA(rna_tcr, verbose = FALSE)

# Harmonize
rna_tcr <- RunHarmony(rna_tcr, "cohortid", plot_convergence = TRUE)

# Cluster and Project (fewer dims for speed)
rna_tcr <- FindNeighbors(rna_tcr, reduction = "harmony", dims = 1:15)
rna_tcr <- FindClusters(rna_tcr, resolution = 2.0, verbose = FALSE)
rna_tcr <- RunUMAP(rna_tcr, reduction = "harmony", dims = 1:15)

saveRDS(rna_tcr, '../../Seurat_Objects/FROM_STEP_3_CD4_T_Cells/rna_tcr_before_selection.rds')
```

Clusters were examined for expression of genes like CD19, CD8, CD34 etc. to exclude non CD4+ T cells. Some naive T cells were sequenced - these were not filtered out.

# Remove non-CD4 T cell clusters
```{r}
rna_tcr <- readRDS("../../Processed_Data/FROM_STEP_3_CD4_T_Cells/rna_tcr_before_selection.rds")
filtered <- subset(rna_tcr, (seurat_clusters %in% c(34,38,39,40,42)) == FALSE)

saveRDS(filtered, "../../Processed_Data/FROM_STEP_3_CD4_T_Cells/rna_tcr_cd4.rds")
```




